apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 7
  template:
    spec:
      containers:
        - name: orders
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "1"