apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: orders
          resources:
            limits:
              cpu: "2"
            requests:
              cpu: "2"