apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: catalog-mysql
spec:
  template:
    spec:
      volumes:
        - $patch: delete
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp2
        resources:
          requests:
            storage: 30Gi 
        